apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  annotations:
    render.crossplane.io/composition-path: apis/pat/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
  name: configuration-app
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    helm:
      wait: false
    providerConfigName: uptest
    passwordSecretRef:
      namespace: default
      name: configuration-app-mariadb
  writeConnectionSecretToRef:
    name: configuration-app
