apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  annotations:
    render.crossplane.io/composition-path: apis/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
  name: configuration-app
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    providerConfigName: uptest
    helm:
      values:
        ghostBlogTitle: Upbound Rocks!
        ghostHost: upboundrocks.cloud
        service:
          type: ClusterIP
        persistence:
          enabled: false
        mysql:
          primary:
            persistence:
              enabled: false
          enabled: true
  writeConnectionSecretToRef:
    name: configuration-app
