apiVersion: platform.upbound.io/v1alpha1
kind: XApp
metadata:
  name: configuration-app
  namespace: default
spec:
  #compositeDeletePolicy: Foreground
  parameters:
    helm:
      wait: false
    providerConfigName: uptest
    passwordSecretRef:
      namespace: default
      name: configuration-app-mariadb
  writeConnectionSecretToRef:
    name: configuration-app
    namespace: default
