apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xapps.platform.upbound.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: platform.upbound.io
  names:
    kind: XApp
    plural: xapps
  claimNames:
    kind: App
    plural: apps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: App configuration parameters.
                  properties:
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                    helm:
                      type: object
                      description: Configuration for operators.
                      properties:
                        chart:
                          type: object
                          description: Configuration for the Helm Chart
                          properties:
                            name:
                              type: string
                              description: chart name
                            repo:
                              type: string
                              description: chart repo
                            version:
                              type: string
                              description: chart version
                        values:
                          type: object
                          description: Values for the Helm Chart
                          x-kubernetes-preserve-unknown-fields: true
                        set:
                          type: array
                          description: Parameters for the Helm Chart
                          items:
                            type: object
                            description: Values for the Helm Chart
                            x-kubernetes-preserve-unknown-fields: true
                  required:
                    - providerConfigName
