apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: configuration-app
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
    test-label: test-value
spec:
  parameters:
    helm:
      chart:
        name: ghost
        repo: "oci://registry-1.docker.io/bitnamicharts"
        version: 25.0.4
      wait: false
    providerConfigName: uptest
    passwordSecretRef:
      namespace: default
      name: configuration-app-mariadb

