apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: configuration-app
  namespace: default
spec:
  parameters:
    helm:
      chart:
        name: ghost
        repo: "https://charts.bitnami.com/bitnami"
        version: 23.0.25
      wait: false
    providerConfigName: uptest
    passwordSecretRef:
      namespace: default
      name: configuration-app-mariadb

