apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: configuration-app
  namespace: default
spec:
  parameters:
    helm:
      wait: false
    providerConfigName: uptest
    passwordSecretRef:
      namespace: default
      name: configuration-app-mariadb

